### ISSUE TITLE
Unable to log in to FB

### ISSUE THREAD

**Issue by NazarOstrovskiy** [Newgarden-Solutions/google_my_business#36]

**Comment by NazarOstrovskiy** [comment]
Summary: Unable to log in to the app via facebook account from Android device
Steps:
1. Reopen the app
2. Staying on the Log In screen tap "Увійти з Facebook"

Actual result:
Some modal windows appears and then disappears quickly

Expected result:
Login with Facebook dialog should be shown

Environment:
Phone, Android version

Note: Issue isn't reproducible with IOS devices

**Comment by OlegNovosad** [comment]
Looks like wrong repo used for defect report
